
services:
  db_dev:
    image: postgres:16-alpine
    container_name: postgres_dev
    env_file:
      - .env 
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" 
    volumes:
      - dev_pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-U', '${DB_USER}', "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5



  db_test:
    image: postgres:16-alpine
    container_name: postgres_test
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
    ports:
      - "5433:5432" 
    volumes:
      - test_pgdata:/var/lib/postgresql/data 
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-U', '${TEST_DB_USER}', "-d", "${TEST_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5




volumes:
  dev_pgdata:
  test_pgdata: